version: "3.8"
services:
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: "teste-incentive"
      MYSQL_ROOT_PASSWORD: "qtc40zR5e9HdQXayLzbvBA"
    ports:
      - "3306:3306"
    expose:
      - "3306"
    volumes:
      - my-db:/var/lib/mysql
volumes:
  my-db:
